apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeservice-deployment
spec:
  selector:
    matchLabels:
      app: timeservice
  replicas: 1
  template:
    metadata:
      labels:
        app: timeservice
    spec:
      containers:
      - name: timeservice
        image: gcr.io/personal-kube-218620/timeservice:${TAG}
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: timeservice-service
spec:
  type: LoadBalancer
  selector:
    app: timeservice
  ports:
  - protocol: TCP
    port: 80 # External port that is mapped to pod port
    targetPort: 8080 # Port from the pod
