apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeservice
  labels:
    app: timeservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeservice
  template:
    metadata:
      labels:
        app: timeservice
    spec:
      containers:
      - name: timeservice
        image: gcr.io/personal-kube-218620/timeservice:${TAG}
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: timeservice
spec:
  selector:
    app: timeservice
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
